on:
  push:
    branches:
    - master
    - release/*
    - update-gradle
  pull_request:
    branches:
    - master
jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1.1.0
